export const urlAndLabel = [
    ["https://openmoji.org/data/color/svg/1F9EC.svg", ["DNA structure", "CRISPR-Cas9 research"]], 
    ["https://openmoji.org/data/color/svg/1FAB8.svg", ["coral reef restoration", "ocean acidification"]],
    ["https://openmoji.org/data/color/svg/1F332.svg", ["photosynthesis", "carbon sinks"]],
    ["https://openmoji.org/data/color/svg/1F9A0.svg", ["evolution of SARS-CoV-2", "mRNA vaccine design"]],
    ["https://openmoji.org/data/color/svg/1F98A.svg", ["fox adaptive traits", "interspecies competition"]],
]

export const usernames = ["ribosome", "mitochondria", "chloroplast", "nucleus", "rough-ER", "smooth-ER", "golgi-body", "lysosome", "cytoskeleton"]

export const ngssLifeScience = [
    "Construct an explanation based on evidence for how the structure of DNA determines the structure of proteins, which carry out the essential functions of life through systems of specialized cells",
    "Develop and use a model to illustrate the hierarchical organization of interacting systems that provide specific functions within multicellular organisms",
    "Plan and conduct an investigation to provide evidence that feedback mechanisms maintain homeostasis",
    "Use a model to illustrate how photosynthesis transforms light energy into stored chemical energy",
    "Construct and revise an explanation based on evidence for how carbon, hydrogen, and oxygen from sugar molecules may combine with other elements to form amino acids and/or other large carbon-based molecules",
    "Use a model to illustrate that cellular respiration is a chemical process whereby the bonds of food molecules and oxygen molecules are broken and the bonds in new compounds are formed, resulting in a net transfer of energy",
    "Construct and revise an explanation based on evidence for the cycling of matter and flow of energy in aerobic and anaerobic conditions",
    "Use mathematical representations to support claims for the cycling of matter and flow of energy among organisms in an ecosystem",
    "Develop a model to illustrate the role of photosynthesis and cellular respiration in the cycling of carbon among the biosphere, atmosphere, hydrosphere, and geosphere",
    "Use mathematical and/or computational representations to support explanations of factors that affect carrying capacity of ecosystems at different scales",
    "Use mathematical representations to support and revise explanations based on evidence about factors affecting biodiversity and populations in ecosystems of different scales",
    "Evaluate claims, evidence, and reasoning that the complex interactions in ecosystems maintain relatively consistent numbers and types of organisms in stable conditions, but changing conditions may result in a new ecosystem",
    "Design, evaluate, and refine a solution for reducing the impacts of human activities on the environment and biodiversity",
    "Evaluate evidence for the role of group behavior on individual and species' chances to survive and reproduce",
    "Create or revise a simulation to test a solution to mitigate adverse impacts of human activity on biodiversity",
    "Construct an explanation based on evidence for how the structure of DNA determines the structure of proteins, which carry out the essential functions of life through systems of specialized cells",
    "Develop and use a model to illustrate the hierarchical organization of interacting systems that provide specific functions within multicellular organisms",
    "Plan and conduct an investigation to provide evidence that feedback mechanisms maintain homeostasis",
    "Use a model to illustrate the role of cellular division (mitosis) and differentiation in producing and maintaining complex organisms",
    "Use a model to illustrate how photosynthesis transforms light energy into stored chemical energy",
    "Construct and revise an explanation based on evidence for how carbon, hydrogen, and oxygen from sugar molecules may combine with other elements to form amino acids and/or other large carbon-based molecules",
    "Use a model to illustrate that cellular respiration is a chemical process whereby the bonds of food molecules and oxygen molecules are broken and the bonds in new compounds are formed, resulting in a net transfer of energy",
    "Use mathematical and/or computational representations to support explanations of factors that affect carrying capacity of ecosystems at different scales",
    "Use mathematical representations to support and revise explanations based on evidence about factors affecting biodiversity and populations in ecosystems of different scales",
    "Construct and revise an explanation based on evidence for the cycling of matter and flow of energy in aerobic and anaerobic conditions",
    "Use mathematical representations to support claims for the cycling of matter and flow of energy among organisms in an ecosystem",
    "Develop a model to illustrate the role of photosynthesis and cellular respiration in the cycling of carbon among the biosphere, atmosphere, hydrosphere, and geosphere",
    "Evaluate claims, evidence, and reasoning that the complex interactions in ecosystems maintain relatively consistent numbers and types of organisms in stable conditions, but changing conditions may result in a new ecosystem",
    "Design, evaluate, and refine a solution for reducing the impacts of human activities on the environment and biodiversity",
    "Evaluate evidence for the role of group behavior on individual and species' chances to survive and reproduce",
    "Communicate scientific information that common ancestry and biological evolution are supported by multiple lines of empirical evidence",
    "Construct an explanation based on evidence that the process of evolution primarily results from four factors: (1) the potential for a species to increase in number, (2) the heritable genetic variation of individuals in a species due to mutation and sexual reproduction, (3) competition for limited resources, and (4) the proliferation of those organisms that are better able to survive and reproduce in the environment",
    "Apply concepts of statistics and probability to support explanations that organisms with an advantageous heritable trait tend to increase in proportion to organisms lacking this trait",
    "Construct an explanation based on evidence for how natural selection leads to adaptation of populations",
    "Evaluate the evidence supporting claims that changes in environmental conditions may result in: (1) increases in the number of individuals of some species, (2) the emergence of new species over time, and (3) the extinction of other species",
    "Create or revise a simulation to test a solution to mitigate adverse impacts of human activity on biodiversity"
]